wait(Pattern("aq_status_green.png").similar(0.61), 10)
wait("aq_menustruct_all.png", 10)
click("aq_menustruct_control.png")
wait(2)
click(Pattern("aq_menutabs_control_settings.png").targetOffset(239,10))
wait(2)
click(Pattern("aq_menutabs_control_settings_device_io.png").similar(0.67).targetOffset(-536,35))
wait(2)
click(Pattern("aq_menutabs_control_settings_device_io_dig_ins.png").targetOffset(-293,-16))
wait(2)
wheel(Pattern("aq_menutabs_control_settings_device_io_dig_ins.png").targetOffset(-260,37), Button.WHEEL_UP, 50)
wheel(Pattern("aq_menutabs_control_settings_device_io_dig_ins.png").targetOffset(-260,37), Button.WHEEL_DOWN, 10)
mouseMove("aq_menutabs_control_settings_device_io_dig_ins_di4_act_th.png")
mouseMove(1200, 0)
mouseDown(Button.LEFT)
mouseUp(Button.LEFT)
type("a", Key.CTRL)
type("15.0"+Key.ENTER)
mouseMove("aq_menutabs_control_settings_device_io_dig_ins_di4_rel_th.png")
mouseMove(1200, 0)
mouseDown(Button.LEFT)
mouseUp(Button.LEFT)
type("a", Key.CTRL)
type("10.0"+Key.ENTER)
click(Pattern("aq_menustrip.png").targetOffset(-124,0))
click(Pattern("aq_menustrip_commands_connected.png").targetOffset(-63,-64))
click(Pattern("aq_dialog_write_changes.png").similar(0.85).targetOffset(-223,298))