wait("aq_status_green.png", 10)
wait("aq_menustruct_all.png", 10)
click("aq_menustruct_protection.png")
wait(2)
click(Pattern("aq_menustabs_protection.png").similar(0.55).targetOffset(-234,9))
wait(2)
click(Pattern("aq_menutabs_generator_module.png").targetOffset(-175,-12))
wait(2)
wheel(Pattern("aq_menutabs_generator_module.png").targetOffset(-160,81),  Button.WHEEL_UP, 50)
wheel(Pattern("aq_menutabs_generator_module.png").targetOffset(-179,92), Button.WHEEL_DOWN, 17)
click(Pattern("1692287229908.png").targetOffset(645,-41))
type("a", Key.CTRL)
type("8.5"+Key.ENTER)
click(Pattern("aq_menustrip.png").targetOffset(-121,-1))
click(Pattern("aq_menustrip_commands_connected.png").targetOffset(-80,-64))
click(Pattern("aq_dialog_write_changes.png").similar(0.85).targetOffset(-230,302))
wait(5) # Give some time for the reset pending button to appear
if exists(Pattern("aq_protection_reset_pending.png").similar(0.85)):
    click(Pattern("aq_protection_reset_pending.png").similar(0.85).targetOffset(150,1))
    Do.popup("Waiting 10 seconds for the DUT to reboot", 10)